providers:
  mock:
    class: adapters.mock.MockAdapter
    env: []
    default_model: demo

  hf_deepseek:
    class: adapters.hf_deepseek.HFDeepSeekAdapter
    env:
      - HF_TOKEN
      - HF_MODEL
    default_model: Qwen/Qwen1.5-72B-Chat

  kimi:
    class: adapters.kimi.KimiAdapter
    env:
      - KIMI_API_KEY
    default_model: moonshot-v1-8k

  gigachat:
    class: adapters.gigachat.GigaChatAdapter
    env:
      - GIGACHAT_API_KEY
    default_model: GigaChat-Pro

models:
  hf_openai:
    adapter: hf_openai
    default_model: deepseek-ai/deepseek-coder-6.7b-instruct
    env: HF_TOKEN